// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/ai-finops/ai-finops/services/workflow-service/internal/app"
)

// Initialize builds the service application graph.
func Initialize() (*app.App, func(), error) {
	config, err := provideConfig()
	if err != nil {
		return nil, nil, err
	}
	slogLogger := provideLogger(config)
	pool, err := providePool(config)
	if err != nil {
		return nil, nil, err
	}
	queries := provideQueries(pool)
	client, err := providePricingClient(config)
	if err != nil {
		return nil, nil, err
	}
	clickhouseClient, err := provideClickHouseClient(config)
	if err != nil {
		return nil, nil, err
	}
	service := provideWorkflowService(pool, queries, client, clickhouseClient, config, slogLogger)
	consumer := provideKafkaConsumer(config, service, slogLogger)
	server, err := provideGRPCServer(config, service)
	if err != nil {
		return nil, nil, err
	}
	router := provideRouter(config, slogLogger, queries)
	telemetryShutdown, err := provideTelemetry(config, slogLogger)
	if err != nil {
		return nil, nil, err
	}
	appApp := provideApp(config, slogLogger, router, pool, queries, server, consumer, client, clickhouseClient)
	cleanup := newCleanup(appApp, pool, telemetryShutdown)
	return appApp, cleanup, nil
}