// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/ai-finops/ai-finops/services/identity-service/internal/app"
)

// Initialize builds the service application graph.
func Initialize() (*app.App, func(), error) {
	config, err := provideConfig()
	if err != nil {
		return nil, nil, err
	}
	slogLogger := provideLogger(config)
	pool, err := providePool(config)
	if err != nil {
		return nil, nil, err
	}
	queries := provideQueries(pool)
	keys, err := provideJWTKeys(config)
	if err != nil {
		return nil, nil, err
	}
	service, err := provideAuthService(pool, queries, keys, config, slogLogger)
	if err != nil {
		return nil, nil, err
	}
	authHandler := provideAuthHandler(service)
	server, err := provideGRPCServer(config, service)
	if err != nil {
		return nil, nil, err
	}
	router := provideRouter(config, slogLogger, queries, authHandler)
	telemetryShutdown, err := provideTelemetry(config, slogLogger)
	if err != nil {
		return nil, nil, err
	}
	appApp := provideApp(config, slogLogger, router, pool, queries, server)
	cleanup := newCleanup(appApp, pool, telemetryShutdown)
	return appApp, cleanup, nil
}