// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/ai-finops/ai-finops/services/analytics-service/internal/app"
)

// Initialize builds the service application graph.
func Initialize() (*app.App, func(), error) {
	config, err := provideConfig()
	if err != nil {
		return nil, nil, err
	}
	logger := provideLogger(config)
	pool, err := providePool(config)
	if err != nil {
		return nil, nil, err
	}
	queries := provideQueries(pool)
	client, err := provideClickHouseClient(config)
	if err != nil {
		return nil, nil, err
	}
	service := provideAnalyticsService(client, queries, logger)
	analyticsHandler := provideAnalyticsHandler(service)
	server, err := provideGRPCServer(config, service)
	if err != nil {
		return nil, nil, err
	}
	router := provideRouter(config, logger, queries, analyticsHandler)
	telemetryShutdown, err := provideTelemetry(config, logger)
	if err != nil {
		return nil, nil, err
	}
	appApp := provideApp(config, logger, router, pool, queries, server, client)
	cleanup := newCleanup(appApp, pool, telemetryShutdown)
	return appApp, cleanup, nil
}